# Generated by Django 4.1.7 on 2023-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=255)),
                ("p_image", models.CharField(max_length=255)),
                ("p_price", models.IntegerField()),
                ("p_descripe", models.TextField(max_length=512)),
            ],
        ),
    ]
