# Generated by Django 4.1.7 on 2023-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0003_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="foot",
            name="p_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="foot",
            name="p_end_discount",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="foot",
            name="p_special_price",
            field=models.IntegerField(null=True),
        ),
    ]
