# Generated by Django 4.1.7 on 2023-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0004_foot_p_discount_foot_p_end_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foot",
            name="p_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
