# Generated by Django 4.1.7 on 2023-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0005_foot_p_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="foot",
            name="p_stock",
            field=models.IntegerField(null=True),
        ),
    ]
