# Generated by Django 4.1.7 on 2023-02-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0007_alter_foot_p_special_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foot",
            name="p_stock",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
