# Generated by Django 4.1.7 on 2023-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0009_alter_foot_p_special_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foot",
            name="p_stock",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
