# Generated by Django 4.1.7 on 2023-11-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_jsy3b", "0010_alter_foot_p_stock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
